### PR TITLE
Added home and explore page

### PR DESCRIPTION
**Pull request by jeetsdev**
Added Home and explore page 

- Navbar
- Sidebar to navigate 
- Videos list 
- Filter by categories 

[Preview](https://deploy-preview-1--sudolib.netlify.app/)

### CODE REVIEW

**Review by saketkum11 — APPROVED** [review]
- clean code
- good properties name in Data base
- much understable.
- UX is good.

**Review by pritam-kr — APPROVED** [review]
Your UI looks clean 
- You have created a pure function for thumbnail which is good 
- good naming 
- clean code

**Review by Nikhil-Nirmal — COMMENTED** [review]
Nice clean code.
Easy to understand.

**Review by Nikhil-Nirmal — APPROVED** [review]
Looks good to merge

**Pull request merged**
