### PR TITLE
Added history page

### PR DESCRIPTION
**Pull request by jeetsdev**
## Added history page, functionality and added single video page 
- User can click on a video and watch
- Those videos will be added to history videos 
- User can remove a particular video from history 
- User can clear all the history videos

[Preview]()

### CODE REVIEW

**Review by rahulmistry751 — APPROVED** [review]
Code looks clean and structured

**Review by manismk — APPROVED** [review]
Good naming convention and code is easy to understand. 

Suggestion: You can add the video to history after the user clicks on the iframe in single video page

**Review by Nikhil-Nirmal — APPROVED** [review]
Nice Clean code.

**Comment by Nikhil-Nirmal** [comment]
Looks Good to merge.

**Pull request merged**
